<a href="https://colab.research.google.com/github/gimdiniz/datathon-fase-5-passos-magicos/blob/main/01_visao_geral_base.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Visão Geral da Base de Dados

## 1. Imports Iniciais

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import os

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:.4f}".format)

## 2. Carregamento da Base

In [2]:
#Path do arquivo raw
DATA_PATH = "https://github.com/gimdiniz/datathon-fase-5-passos-magicos/raw/main/data/raw/BASE%20DE%20DADOS%20PEDE%202024%20-%20DATATHON.xlsx"

#leitura arquivo raw, carregando as planilhas em dfs diferentes
df_2022 = pd.read_excel(DATA_PATH, sheet_name='PEDE2022')
df_2023 = pd.read_excel(DATA_PATH, sheet_name='PEDE2023')
df_2024 = pd.read_excel(DATA_PATH, sheet_name='PEDE2024')

#visualização das primeiras linhas
df_2022.head()
df_2023.head()
df_2024.head()

,RA,Fase,INDE 2024,Pedra 2024,Turma,Nome Anonimizado,Data de Nasc,Idade,Gênero,Ano ingresso,Instituição de ensino,Pedra 20,Pedra 21,Pedra 22,Pedra 23,INDE 22,INDE 23,Cg,Cf,Ct,Nº Av,Avaliador1,Rec Av1,Avaliador2,Rec Av2,Avaliador3,Avaliador4,Avaliador5,Avaliador6,IAA,IEG,IPS,IPP,Rec Psicologia,IDA,Mat,Por,Ing,Indicado,Atingiu PV,IPV,IAN,Fase Ideal,Defasagem,Destaque IEG,Destaque IDA,Destaque IPV,Escola,Ativo/ Inativo,Ativo/ Inativo.1
0,RA-1275,ALFA,7.6114,Ametista,ALFA A - G0/G1,Aluno-1275,2016-07-28,8,Masculino,2024,Pública,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,Avaliador-11,NaN,Avaliador-2,NaN,Avaliador-9,NaN,NaN,NaN,10.0020,8.6667,6.2600,5.6250,NaN,8.0000,10.0000,6.0000,NaN,NaN,NaN,5.4467,10.0000,ALFA (1° e 2° ano),0,NaN,NaN,NaN,EE Chácara Florida II,Cursando,Cursando
1,RA-1276,ALFA,8.0029,Topázio,ALFA A - G0/G1,Aluno-1276,2016-10-16,8,Feminino,2024,Pública,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,Avaliador-11,NaN,Avaliador-2,NaN,Avaliador-9,NaN,NaN,NaN,10.0020,9.3333,3.7600,7.5000,NaN,8.0000,10.0000,6.0000,NaN,NaN,NaN,7.0500,10.0000,ALFA (1° e 2° ano),0,NaN,NaN,NaN,EE Chácara Florida II,Cursando,Cursando
2,RA-1277,ALFA,7.9522,Ametista,ALFA A - G0/G1,Aluno-1277,2016-08-16,8,Masculino,2024,Pública,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,Avaliador-11,NaN,Avaliador-2,NaN,Avaliador-9,NaN,NaN,NaN,10.0020,9.0833,3.7600,7.5000,NaN,8.0000,10.0000,6.0000,NaN,NaN,NaN,7.0467,10.0000,ALFA (1° e 2° ano),0,NaN,NaN,NaN,EE Dom Pedro Villas Boas de Souza,Cursando,Cursando
3,RA-868,ALFA,7.1564,Ametista,ALFA A - G0/G1,Aluno-868,2015-11-08,8,Masculino,2023,Pública,NaN,NaN,NaN,Topázio,NaN,8.6389,NaN,NaN,NaN,3,Avaliador-11,NaN,Avaliador-2,NaN,Avaliador-9,NaN,NaN,NaN,8.0020,9.7500,3.7600,6.8750,NaN,7.0000,8.0000,6.0000,NaN,NaN,NaN,7.2133,5.0000,Fase 1 (3° e 4° ano),-1,NaN,NaN,NaN,EE Chácara Florida II,Cursando,Cursando
4,RA-1278,ALFA,5.4442,Quartzo,ALFA A - G0/G1,Aluno-1278,2015-03-22,9,Masculino,2024,Pública,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,Avaliador-11,NaN,Avaliador-2,NaN,Avaliador-9,NaN,NaN,NaN,9.0020,4.1667,3.7600,5.0000,NaN,7.5000,8.0000,7.0000,NaN,NaN,NaN,4.1733,5.0000,Fase 1 (3° e 4° ano),-1,NaN,NaN,NaN,EM Etelvina Delfim Simões,Cursando,Cursando

## 3. Dimensão das Bases

In [3]:
print(f'Número de linhas: {df_2022.shape[0]}')
print(f'Número de colunas: {df_2022.shape[1]}')
print(f'Número de linhas: {df_2023.shape[0]}')
print(f'Número de colunas: {df_2023.shape[1]}')
print(f'Número de linhas: {df_2024.shape[0]}')
print(f'Número de colunas: {df_2024.shape[1]}')

Número de linhas: 860
Número de colunas: 42
Número de linhas: 1014
Número de colunas: 48
Número de linhas: 1156
Número de colunas: 50

- Nota-se que, ao longo do tempo, a quantidade de registros aumentou, assim como o número de colunas.
- Se trata de um volume pequeno para Machine Learning. Isso facilita teste, deploy e explicação. Porém, precisamos ter cuidado com overfitting e avaliação superficial.

## 4. Limpeza e Padronização dos Dados

- Etapa de verificação e correção de nulos, ajuste de datatypes, padronização de colunas e demais ajustes.

- De acordo com a documentação, os índices IAN, IDA, IEG, IAA, IPS, IPP, IPV, INDE e PEDRA trazem informações muito relevantes para detalhar o desempenho dos alunos e sua evolução. Dessa forma, a padronização buscará preservar ao máximo essas características.

###Dados de 2022

In [4]:
df_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 860 entries, 0 to 859
Data columns (total 42 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     860 non-null    object
 1   Fase                   860 non-null    int64
 2   Turma                  860 non-null    object
 3   Nome                   860 non-null    object
 4   Ano nasc               860 non-null    int64
 5   Idade 22               860 non-null    int64
 6   Gênero                 860 non-null    object
 7   Ano ingresso           860 non-null    int64
 8   Instituição de ensino  860 non-null    object
 9   Pedra 20               323 non-null    object
 10  Pedra 21               462 non-null    object
 11  Pedra 22               860 non-null    object
 12  INDE 22                860 non-null    float64
 13  Cg                     860 non-null    int64
 14  Cf                     860 non-null    int64
 15  Ct                     860 non-null    int64
 16  Nº Av                  860 non-null    int64
 17  Avaliador1             860 non-null    object
 18  Rec Av1                860 non-null    object
 19  Avaliador2             860 non-null    object
 20  Rec Av2                860 non-null    object
 21  Avaliador3             534 non-null    object
 22  Rec Av3                860 non-null    object
 23  Avaliador4             310 non-null    object
 24  Rec Av4                296 non-null    object
 25  IAA                    860 non-null    float64
 26  IEG                    860 non-null    float64
 27  IPS                    860 non-null    float64
 28  Rec Psicologia         860 non-null    object
 29  IDA                    860 non-null    float64
 30  Matem                  858 non-null    float64
 31  Portug                 858 non-null    float64
 32  Inglês                 283 non-null    float64
 33  Indicado               860 non-null    object
 34  Atingiu PV             860 non-null    object
 35  IPV                    860 non-null    float64
 36  IAN                    860 non-null    float64
 37  Fase ideal             860 non-null    object
 38  Defas                  860 non-null    int64
 39  Destaque IEG           860 non-null    object
 40  Destaque IDA           860 non-null    object
 41  Destaque IPV           860 non-null    object
dtypes: float64(10), int64(9), object(23)
memory usage: 282.3+ KB

- Percebe-se que das 42 colunas, algumas possuem valores nulos: Pedra 20, Pedra 21, Avaliador3, Avaliador4, Rec Av4, Matem, Portug e Inglês.
No caso dessa fonte, entendemos que remover os nulos pode não ser a melhor alternativa, pois podemos perder informações importantes das demais colunas.

In [5]:
# Listando todas as colunas que não possuem valores nulos para referenciar posteriormente
colunas_limpas_2022 = df_2022.columns[df_2022.isna().sum() == 0].tolist()

print(f"Total de colunas sem nulos no df_2022: {len(colunas_limpas_2022)}")
print(colunas_limpas_2022)

Total de colunas sem nulos no df_2022: 34
['RA', 'Fase', 'Turma', 'Nome', 'Ano nasc', 'Idade 22', 'Gênero', 'Ano ingresso', 'Instituição de ensino', 'Pedra 22', 'INDE 22', 'Cg', 'Cf', 'Ct', 'Nº Av', 'Avaliador1', 'Rec Av1', 'Avaliador2', 'Rec Av2', 'Rec Av3', 'IAA', 'IEG', 'IPS', 'Rec Psicologia', 'IDA', 'Indicado', 'Atingiu PV', 'IPV', 'IAN', 'Fase ideal', 'Defas', 'Destaque IEG', 'Destaque IDA', 'Destaque IPV']

- É possível notar que, das colunas de índices de desempenho, somente a coluna IPP não existe.

###Dados de 2023

In [6]:
df_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 48 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     1014 non-null   object
 1   Fase                   1014 non-null   object
 2   INDE 2023              931 non-null    float64
 3   Pedra 2023             931 non-null    object
 4   Turma                  1014 non-null   object
 5   Nome Anonimizado       1014 non-null   object
 6   Data de Nasc           1014 non-null   object
 7   Idade                  1014 non-null   object
 8   Gênero                 1014 non-null   object
 9   Ano ingresso           1014 non-null   int64
 10  Instituição de ensino  1014 non-null   object
 11  Pedra 20               240 non-null    object
 12  Pedra 21               335 non-null    object
 13  Pedra 22               600 non-null    object
 14  Pedra 23               0 non-null      float64
 15  INDE 22                600 non-null    float64
 16  INDE 23                0 non-null      float64
 17  Cg                     0 non-null      float64
 18  Cf                     0 non-null      float64
 19  Ct                     0 non-null      float64
 20  Nº Av                  938 non-null    float64
 21  Avaliador1             938 non-null    object
 22  Rec Av1                0 non-null      float64
 23  Avaliador2             938 non-null    object
 24  Rec Av2                0 non-null      float64
 25  Avaliador3             707 non-null    object
 26  Rec Av3                0 non-null      float64
 27  Avaliador4             334 non-null    object
 28  Rec Av4                0 non-null      float64
 29  IAA                    951 non-null    float64
 30  IEG                    938 non-null    float64
 31  IPS                    945 non-null    float64
 32  IPP                    938 non-null    float64
 33  Rec Psicologia         0 non-null      float64
 34  IDA                    937 non-null    float64
 35  Mat                    937 non-null    float64
 36  Por                    937 non-null    float64
 37  Ing                    334 non-null    float64
 38  Indicado               0 non-null      float64
 39  Atingiu PV             0 non-null      float64
 40  IPV                    938 non-null    float64
 41  IAN                    1014 non-null   float64
 42  Fase Ideal             1014 non-null   object
 43  Defasagem              1014 non-null   int64
 44  Destaque IEG           0 non-null      float64
 45  Destaque IDA           0 non-null      float64
 46  Destaque IPV           0 non-null      float64
 47  Destaque IPV.1         0 non-null      float64
dtypes: float64(29), int64(2), object(17)
memory usage: 380.4+ KB

- Percebe-se que o df de 2023 está mais defasado, com diversas colunas com muitos ou somente nulos.

In [7]:
# Listando todas as colunas que não possuem valores nulos para referenciar posteriormente
colunas_limpas_2023 = df_2023.columns[df_2023.isna().sum() == 0].tolist()

print(f"Total de colunas sem nulos no df_2023: {len(colunas_limpas_2023)}")
print(colunas_limpas_2023)

Total de colunas sem nulos no df_2023: 12
['RA', 'Fase', 'Turma', 'Nome Anonimizado', 'Data de Nasc', 'Idade', 'Gênero', 'Ano ingresso', 'Instituição de ensino', 'IAN', 'Fase Ideal', 'Defasagem']

- Como boa parte das colunas possui algum valor nulo, inclusive de indicadores, teremos que trabalhar a remoção das linhas com registros nulos. Nesse caso, não é seguro utilizar técnicas de substituição dos nulos, dado que assumir algum tipo de desempenho pode distorcer nossas análise e, posteriormente, o modelo preditivo.

In [8]:
# Deletando linhas que possuem dados nulos em colunas mandatórias ou somente dados nulos
df_2023_ajuste = (
    df_2023
    # Remove as LINHAS onde faltam esses indicadores essenciais
    .dropna(subset=['IAN', 'IDA', 'IEG', 'IAA', 'IPS', 'IPP', 'IPV', 'INDE 2023', 'Pedra 2023'])
    # Remove as COLUNAS que ficaram apenas com valores nulos
    .dropna(axis=1, how='all')
    # Reseta o índice para cobrir os buracos das linhas excluídas
    .reset_index(drop=True)
)

df_2023_ajuste.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 931 entries, 0 to 930
Data columns (total 32 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     931 non-null    object
 1   Fase                   931 non-null    object
 2   INDE 2023              931 non-null    float64
 3   Pedra 2023             931 non-null    object
 4   Turma                  931 non-null    object
 5   Nome Anonimizado       931 non-null    object
 6   Data de Nasc           931 non-null    object
 7   Idade                  931 non-null    object
 8   Gênero                 931 non-null    object
 9   Ano ingresso           931 non-null    int64
 10  Instituição de ensino  931 non-null    object
 11  Pedra 20               220 non-null    object
 12  Pedra 21               311 non-null    object
 13  Pedra 22               570 non-null    object
 14  INDE 22                570 non-null    float64
 15  Nº Av                  931 non-null    float64
 16  Avaliador1             931 non-null    object
 17  Avaliador2             931 non-null    object
 18  Avaliador3             700 non-null    object
 19  Avaliador4             328 non-null    object
 20  IAA                    931 non-null    float64
 21  IEG                    931 non-null    float64
 22  IPS                    931 non-null    float64
 23  IPP                    931 non-null    float64
 24  IDA                    931 non-null    float64
 25  Mat                    931 non-null    float64
 26  Por                    931 non-null    float64
 27  Ing                    328 non-null    float64
 28  IPV                    931 non-null    float64
 29  IAN                    931 non-null    float64
 30  Fase Ideal             931 non-null    object
 31  Defasagem              931 non-null    int64
dtypes: float64(13), int64(2), object(17)
memory usage: 232.9+ KB

###Dados de 2024

In [9]:
df_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 50 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     1156 non-null   object
 1   Fase                   1156 non-null   object
 2   INDE 2024              1092 non-null   object
 3   Pedra 2024             1092 non-null   object
 4   Turma                  1156 non-null   object
 5   Nome Anonimizado       1156 non-null   object
 6   Data de Nasc           1156 non-null   datetime64[ns]
 7   Idade                  1156 non-null   int64
 8   Gênero                 1156 non-null   object
 9   Ano ingresso           1156 non-null   int64
 10  Instituição de ensino  1155 non-null   object
 11  Pedra 20               191 non-null    object
 12  Pedra 21               264 non-null    object
 13  Pedra 22               472 non-null    object
 14  Pedra 23               690 non-null    object
 15  INDE 22                472 non-null    float64
 16  INDE 23                690 non-null    float64
 17  Cg                     0 non-null      float64
 18  Cf                     0 non-null      float64
 19  Ct                     0 non-null      float64
 20  Nº Av                  1156 non-null   int64
 21  Avaliador1             1029 non-null   object
 22  Rec Av1                0 non-null      float64
 23  Avaliador2             1029 non-null   object
 24  Rec Av2                0 non-null      float64
 25  Avaliador3             793 non-null    object
 26  Avaliador4             407 non-null    object
 27  Avaliador5             148 non-null    object
 28  Avaliador6             6 non-null      object
 29  IAA                    1054 non-null   float64
 30  IEG                    1156 non-null   float64
 31  IPS                    1054 non-null   float64
 32  IPP                    1054 non-null   float64
 33  Rec Psicologia         0 non-null      float64
 34  IDA                    1055 non-null   float64
 35  Mat                    1051 non-null   float64
 36  Por                    1050 non-null   float64
 37  Ing                    474 non-null    float64
 38  Indicado               0 non-null      float64
 39  Atingiu PV             0 non-null      float64
 40  IPV                    1054 non-null   float64
 41  IAN                    1156 non-null   float64
 42  Fase Ideal             1156 non-null   object
 43  Defasagem              1156 non-null   int64
 44  Destaque IEG           0 non-null      float64
 45  Destaque IDA           0 non-null      float64
 46  Destaque IPV           0 non-null      float64
 47  Escola                 1155 non-null   object
 48  Ativo/ Inativo         1156 non-null   object
 49  Ativo/ Inativo.1       1156 non-null   object
dtypes: datetime64[ns](1), float64(23), int64(4), object(22)
memory usage: 451.7+ KB

Os dados de 2024 parecem estar mais parecidos com os de 2023, com algumas colunas com diversos nulos.

In [10]:
# Listando todas as colunas que não possuem valores nulos para referenciar posteriormente
colunas_limpas_2024 = df_2024.columns[df_2024.isna().sum() == 0].tolist()

print(f"Total de colunas sem nulos no df_2024: {len(colunas_limpas_2024)}")
print(colunas_limpas_2024)

Total de colunas sem nulos no df_2024: 15
['RA', 'Fase', 'Turma', 'Nome Anonimizado', 'Data de Nasc', 'Idade', 'Gênero', 'Ano ingresso', 'Nº Av', 'IEG', 'IAN', 'Fase Ideal', 'Defasagem', 'Ativo/ Inativo', 'Ativo/ Inativo.1']

Da mesma forma, removeremos somente linhas de colunas mandatórias com valores nulos.

In [11]:
# Deletando linhas que possuem dados nulos em colunas mandatórias
df_2024_ajuste = (
    df_2024
    # Remove as LINHAS onde faltam esses indicadores essenciais
    .dropna(subset=['IAN', 'IDA', 'IEG', 'IAA', 'IPS', 'IPP', 'IPV', 'INDE 2024', 'Pedra 2024'])
    # Remove as COLUNAS que ficaram apenas com valores nulos
    .dropna(axis=1, how='all')
    # Reseta o índice para cobrir os buracos das linhas excluídas
    .reset_index(drop=True)
)
df_2024_ajuste.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054 entries, 0 to 1053
Data columns (total 39 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     1054 non-null   object
 1   Fase                   1054 non-null   object
 2   INDE 2024              1054 non-null   object
 3   Pedra 2024             1054 non-null   object
 4   Turma                  1054 non-null   object
 5   Nome Anonimizado       1054 non-null   object
 6   Data de Nasc           1054 non-null   datetime64[ns]
 7   Idade                  1054 non-null   int64
 8   Gênero                 1054 non-null   object
 9   Ano ingresso           1054 non-null   int64
 10  Instituição de ensino  1053 non-null   object
 11  Pedra 20               179 non-null    object
 12  Pedra 21               247 non-null    object
 13  Pedra 22               445 non-null    object
 14  Pedra 23               678 non-null    object
 15  INDE 22                445 non-null    float64
 16  INDE 23                678 non-null    float64
 17  Nº Av                  1054 non-null   int64
 18  Avaliador1             1029 non-null   object
 19  Avaliador2             1029 non-null   object
 20  Avaliador3             793 non-null    object
 21  Avaliador4             407 non-null    object
 22  Avaliador5             148 non-null    object
 23  Avaliador6             6 non-null      object
 24  IAA                    1054 non-null   float64
 25  IEG                    1054 non-null   float64
 26  IPS                    1054 non-null   float64
 27  IPP                    1054 non-null   float64
 28  IDA                    1054 non-null   float64
 29  Mat                    1050 non-null   float64
 30  Por                    1049 non-null   float64
 31  Ing                    473 non-null    float64
 32  IPV                    1054 non-null   float64
 33  IAN                    1054 non-null   float64
 34  Fase Ideal             1054 non-null   object
 35  Defasagem              1054 non-null   int64
 36  Escola                 1053 non-null   object
 37  Ativo/ Inativo         1054 non-null   object
 38  Ativo/ Inativo.1       1054 non-null   object
dtypes: datetime64[ns](1), float64(12), int64(4), object(22)
memory usage: 321.3+ KB

###Seleção de colunas e padronização de nomes de colunas

Utilizaremos uma função que compara as colunas dos DFs, indicando as diferenças e semelhanças entre elas.

In [12]:
def comparar_colunas_dfs(df1, df2, df3, nomes=['DF1', 'DF2', 'DF3']):
    # Transforma as listas de colunas em 'conjuntos' (sets)
    cols1 = set(df1.columns)
    cols2 = set(df2.columns)
    cols3 = set(df3.columns)

    # 1. Colunas IGUAIS: Interseção (presentes nos 3 simultaneamente)
    comuns = cols1 & cols2 & cols3

    # 2. Todas as colunas existentes somadas (União)
    todas = cols1 | cols2 | cols3

    # 3. Colunas DIFERENTES: Tudo que existe, menos o que é comum a todos
    diferentes = todas - comuns

    # --- Relatório Visual ---
    print(f"Colunas presentes em TODOS ({len(comuns)}):")
    print(list(comuns))
    print("\n")

    print(f"Colunas DIFERENTES (não estão nos três) ({len(diferentes)}):")
    # Para facilitar, mostra em qual DF a coluna diferente está
    for col in diferentes:
        onde_tem = []
        if col in cols1: onde_tem.append(nomes[0])
        if col in cols2: onde_tem.append(nomes[1])
        if col in cols3: onde_tem.append(nomes[2])
        print(f"   - '{col}' (Presente em: {', '.join(onde_tem)})")

    return list(comuns), list(diferentes)

In [13]:
# Chamando a função e guardando os resultados em duas variáveis
colunas_iguais, colunas_diferentes = comparar_colunas_dfs(
    df1=df_2022,
    df2=df_2023_ajuste,
    df3=df_2024_ajuste,
    nomes=['2022', '2023', '2024']
)

Colunas presentes em TODOS (21):
['INDE 22', 'Nº Av', 'IAA', 'Turma', 'RA', 'IDA', 'IAN', 'Pedra 20', 'Avaliador4', 'IPV', 'IPS', 'Pedra 21', 'Avaliador3', 'Ano ingresso', 'Avaliador2', 'Instituição de ensino', 'IEG', 'Avaliador1', 'Fase', 'Gênero', 'Pedra 22']


Colunas DIFERENTES (não estão nos três) (41):
   - 'Rec Av2' (Presente em: 2022)
   - 'Destaque IEG' (Presente em: 2022)
   - 'Mat' (Presente em: 2023, 2024)
   - 'Cg' (Presente em: 2022)
   - 'Cf' (Presente em: 2022)
   - 'INDE 2024' (Presente em: 2024)
   - 'Fase Ideal' (Presente em: 2023, 2024)
   - 'Escola' (Presente em: 2024)
   - 'Rec Av1' (Presente em: 2022)
   - 'Ano nasc' (Presente em: 2022)
   - 'Por' (Presente em: 2023, 2024)
   - 'Rec Av4' (Presente em: 2022)
   - 'Fase ideal' (Presente em: 2022)
   - 'Ing' (Presente em: 2023, 2024)
   - 'Pedra 23' (Presente em: 2024)
   - 'Atingiu PV' (Presente em: 2022)
   - 'Pedra 2023' (Presente em: 2023)
   - 'Indicado' (Presente em: 2022)
   - 'Matem' (Presente em: 2022)
   - 'Pedra 2024' (Presente em: 2024)
   - 'Nome' (Presente em: 2022)
   - 'Idade 22' (Presente em: 2022)
   - 'Data de Nasc' (Presente em: 2023, 2024)
   - 'Portug' (Presente em: 2022)
   - 'INDE 2023' (Presente em: 2023)
   - 'Defas' (Presente em: 2022)
   - 'Destaque IPV' (Presente em: 2022)
   - 'Rec Psicologia' (Presente em: 2022)
   - 'INDE 23' (Presente em: 2024)
   - 'Ativo/ Inativo' (Presente em: 2024)
   - 'Ct' (Presente em: 2022)
   - 'IPP' (Presente em: 2023, 2024)
   - 'Ativo/ Inativo.1' (Presente em: 2024)
   - 'Nome Anonimizado' (Presente em: 2023, 2024)
   - 'Rec Av3' (Presente em: 2022)
   - 'Avaliador5' (Presente em: 2024)
   - 'Idade' (Presente em: 2023, 2024)
   - 'Defasagem' (Presente em: 2023, 2024)
   - 'Avaliador6' (Presente em: 2024)
   - 'Inglês' (Presente em: 2022)
   - 'Destaque IDA' (Presente em: 2022)

É necessário alterar o nome de algumas colunas, que existem para os três anos, mas estão com nomes divergentes (por exemplo, Defas e Defasagem).
No entanto, notamos que existem as colunas [Data de Nasc] em 2023 e 2024, e [Ano nasc] 2022, que potencialmente tem padrões diferentes de dados.

In [14]:
df_comparacao = pd.concat([
    df_2022['Ano nasc'].rename('Nascimento (Base 2022)'),
    df_2023_ajuste['Data de Nasc'].rename('Nascimento (Base 2023)'),
    df_2024_ajuste['Data de Nasc'].rename('Nascimento (Base 2024)')
], axis=1)

df_comparacao.head(10)

   Nascimento (Base 2022) Nascimento (Base 2023) Nascimento (Base 2024)
0               2003.0000              6/17/2015             2016-07-28
1               2005.0000              5/31/2014             2016-10-16
2               2005.0000              2/25/2016             2016-08-16
3               2005.0000    2015-12-03 00:00:00             2015-11-08
4               2005.0000             11/13/2014             2015-03-22
5               2004.0000    2016-10-02 00:00:00             2015-06-10
6               2004.0000              6/29/2015             2015-06-17
7               2002.0000    2015-08-11 00:00:00             2014-05-31
8               2004.0000              1/15/2015             2015-05-17
9               2004.0000             10/20/2014             2015-02-20

In [15]:
#Extraindo o ano para normalização dos dados de nascimento
#em 2023, os dados estão no padrão mês/dia
df_2023_ajuste['Data de Nasc'] = pd.to_datetime(df_2023_ajuste['Data de Nasc'], format='%m/%d/%Y', errors='coerce').dt.year

#já em 2024, seguem o padrão dia/mês
df_2024_ajuste['Data de Nasc'] = pd.to_datetime(df_2024_ajuste['Data de Nasc'], format='%d/%m/%Y', errors='coerce').dt.year

In [16]:
df_comparacao = pd.concat([
    df_2022['Ano nasc'].rename('Nascimento (Base 2022)'),
    df_2023_ajuste['Data de Nasc'].rename('Nascimento (Base 2023)'),
    df_2024_ajuste['Data de Nasc'].rename('Nascimento (Base 2024)')
], axis=1)

df_comparacao.head(10)

   Nascimento (Base 2022)  Nascimento (Base 2023)  Nascimento (Base 2024)
0               2003.0000               2015.0000                    2016
1               2005.0000               2014.0000                    2016
2               2005.0000               2016.0000                    2016
3               2005.0000               2015.0000                    2015
4               2005.0000               2014.0000                    2015
5               2004.0000               2016.0000                    2015
6               2004.0000               2015.0000                    2015
7               2002.0000               2015.0000                    2014
8               2004.0000               2015.0000                    2015
9               2004.0000               2014.0000                    2015

In [17]:
# Definindo as regras para a base de 2022
dic_2022 = {
    'Fase ideal': 'Fase Ideal',
    'Matem': 'Mat',
    'Portug': 'Por',
    'Inglês': 'Ing',
    'Defas': 'Defasagem',
    'Nome': 'Nome Anonimizado',
    'Idade 22': 'Idade',
    'Pedra 22' : 'Pedra' ,
    'Ano nasc': 'Ano Nascimento' ,
    'INDE 22' : 'INDE'
}

# Definindo as regras para a base de 2023
dic_2023 = {
    'INDE 2023': 'INDE',
    # 'INDE 23': 'INDE',
    'Pedra 2023': 'Pedra',
    # 'Pedra 23': 'Pedra',
    'Data de Nasc': 'Ano Nascimento'
}

# Definindo as regras para a base de 2024
dic_2024 = {
    'INDE 2024': 'INDE',
    # 'INDE 23': 'INDE',
    'Pedra 2024': 'Pedra',
    'Data de Nasc': 'Ano Nascimento'
}

# Aplicando a transformação
df_2022 = df_2022.rename(columns=dic_2022)
df_2023_ajuste = df_2023_ajuste.rename(columns=dic_2023)
df_2024_ajuste = df_2024_ajuste.rename(columns=dic_2024)

In [18]:
#Rodando novamente o comparativo entre colunas nos dfs

colunas_iguais, colunas_diferentes = comparar_colunas_dfs(
    df1=df_2022,
    df2=df_2023_ajuste,
    df3=df_2024_ajuste,
    nomes=['2022', '2023', '2024']
)

Colunas presentes em TODOS (29):
['Nº Av', 'Mat', 'IAA', 'Fase Ideal', 'Turma', 'RA', 'INDE', 'Por', 'Ing', 'IDA', 'IAN', 'Pedra 20', 'Avaliador4', 'Ano Nascimento', 'IPV', 'IPS', 'Pedra 21', 'Avaliador3', 'Ano ingresso', 'Pedra', 'Avaliador2', 'Instituição de ensino', 'Nome Anonimizado', 'IEG', 'Idade', 'Avaliador1', 'Fase', 'Defasagem', 'Gênero']


Colunas DIFERENTES (não estão nos três) (23):
   - 'Rec Av2' (Presente em: 2022)
   - 'Destaque IEG' (Presente em: 2022)
   - 'INDE 22' (Presente em: 2023, 2024)
   - 'Cg' (Presente em: 2022)
   - 'Cf' (Presente em: 2022)
   - 'Escola' (Presente em: 2024)
   - 'Rec Av1' (Presente em: 2022)
   - 'Rec Av4' (Presente em: 2022)
   - 'Pedra 23' (Presente em: 2024)
   - 'Atingiu PV' (Presente em: 2022)
   - 'Indicado' (Presente em: 2022)
   - 'Destaque IPV' (Presente em: 2022)
   - 'Rec Psicologia' (Presente em: 2022)
   - 'INDE 23' (Presente em: 2024)
   - 'Ativo/ Inativo' (Presente em: 2024)
   - 'Ct' (Presente em: 2022)
   - 'IPP' (Presente em: 2023, 2024)
   - 'Ativo/ Inativo.1' (Presente em: 2024)
   - 'Rec Av3' (Presente em: 2022)
   - 'Avaliador5' (Presente em: 2024)
   - 'Avaliador6' (Presente em: 2024)
   - 'Destaque IDA' (Presente em: 2022)
   - 'Pedra 22' (Presente em: 2023, 2024)

Para garantir uma análise sólida, vamos focar em avaliar indicadores em comum entre os três anos.

In [19]:
# Descobre a interseção
colunas_comuns = list(set(df_2022.columns) & set(df_2023_ajuste.columns) & set(df_2024_ajuste.columns))

print(f"Total de colunas em comum que serão mantidas: {len(colunas_comuns)}")

# Filtra cada base para ficar APENAS com essas colunas
df_22_comum = df_2022[colunas_comuns].copy()
df_23_comum = df_2023_ajuste[colunas_comuns].copy()
df_24_comum = df_2024_ajuste[colunas_comuns].copy()

Total de colunas em comum que serão mantidas: 29

In [20]:
colunas_iguais, colunas_diferentes = comparar_colunas_dfs(
    df1=df_22_comum,
    df2=df_23_comum,
    df3=df_24_comum,
    nomes=['2022', '2023', '2024']
)

Colunas presentes em TODOS (29):
['Nº Av', 'Mat', 'IAA', 'Fase Ideal', 'Turma', 'RA', 'INDE', 'Por', 'Ing', 'IDA', 'IAN', 'Pedra 20', 'Avaliador4', 'Ano Nascimento', 'IPV', 'IPS', 'Pedra 21', 'Avaliador3', 'Ano ingresso', 'Pedra', 'Avaliador2', 'Instituição de ensino', 'Nome Anonimizado', 'IEG', 'Idade', 'Avaliador1', 'Fase', 'Defasagem', 'Gênero']


Colunas DIFERENTES (não estão nos três) (0):

### Corrigindo Datatypes

In [21]:
def comparar_dtypes_dfs(df1, df2, df3, nomes=['2022', '2023', '2024']):
    # Cria um DataFrame onde cada coluna é o tipo de dado de um ano específico
    df_comparativo = pd.DataFrame({
        nomes[0]: df1.dtypes,
        nomes[1]: df2.dtypes,
        nomes[2]: df3.dtypes
    })

    # Cria uma regra para checar se o tipo do Ano 1 é igual ao Ano 2 E igual ao Ano 3
    # Se forem todos iguais, 'Divergente' será False. Se houver diferença, será True.
    df_comparativo['Divergente'] = ~(
        (df_comparativo[nomes[0]] == df_comparativo[nomes[1]]) &
        (df_comparativo[nomes[1]] == df_comparativo[nomes[2]])
    )

    # --- Relatório Visual ---
    divergencias = df_comparativo[df_comparativo['Divergente'] == True]

    print("RELATÓRIO DE COMPATIBILIDADE DE TIPOS")
    print("-" * 50)

    if len(divergencias) == 0:
        print("Todas as colunas compartilham os mesmos tipos de dados nos 3 anos.")
    else:
        print(f"Encontradas {len(divergencias)} colunas com tipos divergentes")
        print(divergencias.drop(columns=['Divergente']))

    return df_comparativo

In [22]:
relatorio_tipos = comparar_dtypes_dfs(df_22_comum, df_23_comum, df_24_comum)

RELATÓRIO DE COMPATIBILIDADE DE TIPOS
--------------------------------------------------
Encontradas 5 colunas com tipos divergentes
                   2022     2023    2024
Nº Av             int64  float64   int64
INDE            float64  float64  object
Ano Nascimento    int64    int32   int32
Idade             int64   object   int64
Fase              int64   object  object

In [23]:
# CORREÇÃO 2022
df_22_comum['Fase'] = df_22_comum['Fase'].astype(str)  # Garante texto para o mapeamento nominal
df_22_comum['Idade'] = df_22_comum['Idade'].astype('Int64')
df_22_comum['Ano Nascimento'] = df_22_comum['Ano Nascimento'].astype('Int64')
df_22_comum['Nº Av'] = df_22_comum['Nº Av'].astype('Int64')

# CORREÇÃO 2023
df_23_comum['Fase'] = df_23_comum['Fase'].astype(str)
df_23_comum['Idade'] = pd.to_numeric(df_23_comum['Idade'], errors='coerce').astype('Int64')
df_23_comum['Ano Nascimento'] = df_23_comum['Ano Nascimento'].astype('Int64')
df_23_comum['Nº Av'] = df_23_comum['Nº Av'].astype('Int64')

# CORREÇÃO 2024
df_24_comum['INDE'] = pd.to_numeric(df_24_comum['INDE'], errors='coerce')
df_24_comum['Fase'] = df_24_comum['Fase'].astype(str)
df_24_comum['Idade'] = df_24_comum['Idade'].astype('Int64')
df_24_comum['Ano Nascimento'] = df_24_comum['Ano Nascimento'].astype('Int64')
df_24_comum['Nº Av'] = df_24_comum['Nº Av'].astype('Int64')

relatorio_tipos = comparar_dtypes_dfs(df_22_comum, df_23_comum, df_24_comum)

RELATÓRIO DE COMPATIBILIDADE DE TIPOS
--------------------------------------------------
Todas as colunas compartilham os mesmos tipos de dados nos 3 anos.

###Unificando as bases em um único df

In [24]:
# Adicionando a referência de cada dado
df_22_comum['Ano_Referencia'] = 2022
df_23_comum['Ano_Referencia'] = 2023
df_24_comum['Ano_Referencia'] = 2024

df_concat = pd.concat([df_22_comum, df_23_comum, df_24_comum], ignore_index=True)

df_concat.shape
df_concat.head()

,Nº Av,Mat,IAA,Fase Ideal,Turma,RA,INDE,Por,Ing,IDA,IAN,Pedra 20,Avaliador4,Ano Nascimento,IPV,IPS,Pedra 21,Avaliador3,Ano ingresso,Pedra,Avaliador2,Instituição de ensino,Nome Anonimizado,IEG,Idade,Avaliador1,Fase,Defasagem,Gênero,Ano_Referencia
0,4,2.7000,8.3000,Fase 8 (Universitários),A,RA-1,5.7830,3.5000,6.0000,4.0000,5.0000,Ametista,Avaliador-31,2003,7.2780,5.6000,Ametista,Avaliador-28,2016,Quartzo,Avaliador-27,Escola Pública,Aluno-1,4.1000,19,Avaliador-5,7,-1,Menina,2022
1,4,6.3000,8.8000,Fase 7 (3º EM),A,RA-2,7.0550,4.5000,9.7000,6.8000,10.0000,Ametista,Avaliador-31,2005,6.7780,6.3000,Ametista,Avaliador-28,2017,Ametista,Avaliador-27,Rede Decisão,Aluno-2,5.2000,17,Avaliador-5,7,0,Menina,2022
2,4,5.8000,0.0000,Fase 7 (3º EM),A,RA-3,6.5910,4.0000,6.9000,5.6000,10.0000,Ametista,Avaliador-31,2005,7.5560,5.6000,Ametista,Avaliador-28,2016,Ágata,Avaliador-27,Rede Decisão,Aluno-3,7.9000,17,Avaliador-5,7,0,Menina,2022
3,4,2.8000,8.8000,Fase 7 (3º EM),A,RA-4,5.9510,3.5000,8.7000,5.0000,10.0000,Ametista,Avaliador-31,2005,5.2780,5.6000,Ametista,Avaliador-28,2017,Quartzo,Avaliador-27,Rede Decisão,Aluno-4,4.5000,17,Avaliador-5,7,0,Menino,2022
4,4,7.0000,7.9000,Fase 7 (3º EM),A,RA-5,7.4270,2.9000,5.7000,5.2000,10.0000,Ametista,Avaliador-31,2005,7.3890,5.6000,Ametista,Avaliador-28,2016,Ametista,Avaliador-27,Rede Decisão,Aluno-5,8.6000,17,Avaliador-5,7,0,Menina,2022

###Verificando nulos e normalizando nomes e ordens de colunas

In [25]:
df_concat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2845 entries, 0 to 2844
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Nº Av                  2845 non-null   Int64
 1   Mat                    2839 non-null   float64
 2   IAA                    2845 non-null   float64
 3   Fase Ideal             2845 non-null   object
 4   Turma                  2845 non-null   object
 5   RA                     2845 non-null   object
 6   INDE                   2845 non-null   float64
 7   Por                    2838 non-null   float64
 8   Ing                    1084 non-null   float64
 9   IDA                    2845 non-null   float64
 10  IAN                    2845 non-null   float64
 11  Pedra 20               722 non-null    object
 12  Avaliador4             1045 non-null   object
 13  Ano Nascimento         2845 non-null   Int64
 14  IPV                    2845 non-null   float64
 15  IPS                    2845 non-null   float64
 16  Pedra 21               1020 non-null   object
 17  Avaliador3             2027 non-null   object
 18  Ano ingresso           2845 non-null   int64
 19  Pedra                  2845 non-null   object
 20  Avaliador2             2820 non-null   object
 21  Instituição de ensino  2844 non-null   object
 22  Nome Anonimizado       2845 non-null   object
 23  IEG                    2845 non-null   float64
 24  Idade                  2478 non-null   Int64
 25  Avaliador1             2820 non-null   object
 26  Fase                   2845 non-null   object
 27  Defasagem              2845 non-null   int64
 28  Gênero                 2845 non-null   object
 29  Ano_Referencia         2845 non-null   int64
dtypes: Int64(3), float64(10), int64(3), object(14)
memory usage: 675.3+ KB

Para os dados de Idade faltantes, vamos calcular considerando o Ano_Referencia - Ano Nascimento, pois é possível inferir;
Além disso, temos algumas notas de português e matemática faltantes. Vamos trabalhar com interpolate, preservando a distribuição estatística da base;
Só existe um dado faltante de Instituição de Ensino, então vamos preencher com algum registro de escola aleatório;

In [26]:
# Preencher a Idade faltante (Ano Referência - Ano Nascimento)
df_concat['Idade'] = df_concat['Idade'].fillna(df_concat['Ano_Referencia'] - df_concat['Ano Nascimento'])

# Renomear as colunas de Notas
df_concat = df_concat.rename(columns={
    'Mat': 'Nota_Matematica',
    'Por': 'Nota_Portugues'
})

# Completando as Notas com interpolação
df_concat['Nota_Matematica'] = df_concat['Nota_Matematica'].interpolate()
df_concat['Nota_Portugues'] = df_concat['Nota_Portugues'].interpolate()

# Preenchendo a Instituição de Ensino com uma escola aleatória da própria base
escola_aleatoria = df_concat['Instituição de ensino'].dropna().sample(1).values[0]
df_concat['Instituição de ensino'] = df_concat['Instituição de ensino'].fillna(escola_aleatoria)

# Removendo a coluna Nº Av, pois não é possível inferir seu significado sem registro dela no dicionário de dados
if 'Nº Av' in df_concat.columns:
    df_concat = df_concat.drop(columns=['Nº Av'])

# Removendo todas as demais colunas que ainda tenham nulos
df_concat = df_concat.dropna(axis=1)

# Verificação
df_concat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2845 entries, 0 to 2844
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Nota_Matematica        2845 non-null   float64
 1   IAA                    2845 non-null   float64
 2   Fase Ideal             2845 non-null   object
 3   Turma                  2845 non-null   object
 4   RA                     2845 non-null   object
 5   INDE                   2845 non-null   float64
 6   Nota_Portugues         2845 non-null   float64
 7   IDA                    2845 non-null   float64
 8   IAN                    2845 non-null   float64
 9   Ano Nascimento         2845 non-null   Int64
 10  IPV                    2845 non-null   float64
 11  IPS                    2845 non-null   float64
 12  Ano ingresso           2845 non-null   int64
 13  Pedra                  2845 non-null   object
 14  Instituição de ensino  2845 non-null   object
 15  Nome Anonimizado       2845 non-null   object
 16  IEG                    2845 non-null   float64
 17  Idade                  2845 non-null   Int64
 18  Fase                   2845 non-null   object
 19  Defasagem              2845 non-null   int64
 20  Gênero                 2845 non-null   object
 21  Ano_Referencia         2845 non-null   int64
dtypes: Int64(2), float64(9), int64(3), object(8)
memory usage: 494.7+ KB

### Verificar Duplicados

In [27]:
#Checagem geral de duplicados
df_concat.duplicated().sum()

np.int64(0)

In [28]:
#Transforma RA e Nome Anonimizado em texto e remove espaços em branco inúteis no início e no fim, para garantir padronização
df_concat['RA'] = df_concat['RA'].astype(str).str.strip()
df_concat['Nome Anonimizado'] = df_concat['Nome Anonimizado'].astype(str).str.strip()

In [29]:
#Checagem de duplicidade por RA num mesmo ano, por erro de preenchimento, por exemplo
duplicados_mesmo_ano = df_concat[df_concat.duplicated(subset=['RA', 'Ano_Referencia'], keep=False)]

print(f"Total de registros duplicados dentro do mesmo ano: {len(duplicados_mesmo_ano)}")

if len(duplicados_mesmo_ano) > 0:
    print(duplicados_mesmo_ano[['Nome Anonimizado', 'RA', 'Ano_Referencia']].head())

Total de registros duplicados dentro do mesmo ano: 0

In [30]:
#Checagem de duplicidade de mesmo RA ao longo dos anos
historico_alunos_repetidos = df_concat[df_concat.duplicated(subset=['RA'], keep=False)].sort_values(by=['Nome Anonimizado', 'Ano_Referencia'])

historico_alunos_repetidos[['Nome Anonimizado', 'RA', 'Ano_Referencia', 'Fase', 'INDE']].head(15)

     Nome Anonimizado       RA  Ano_Referencia  Fase   INDE
1072       Aluno-1000  RA-1000            2023  ALFA 7.9162
2142       Aluno-1000  RA-1000            2024    1N 8.3648
1074       Aluno-1001  RA-1001            2023  ALFA 8.1162
2144       Aluno-1001  RA-1001            2024    1N 7.7964
1075       Aluno-1002  RA-1002            2023  ALFA 7.9012
1918       Aluno-1002  RA-1002            2024  ALFA 7.9679
1076       Aluno-1003  RA-1003            2023  ALFA 7.6522
1866       Aluno-1003  RA-1003            2024  ALFA 7.6276
1078       Aluno-1004  RA-1004            2023  ALFA 8.3137
1867       Aluno-1004  RA-1004            2024  ALFA 7.8012
1080       Aluno-1006  RA-1006            2023  ALFA 8.5922
1868       Aluno-1006  RA-1006            2024  ALFA 7.0401
1083       Aluno-1008  RA-1008            2023  ALFA 8.1359
1863       Aluno-1008  RA-1008            2024  ALFA 6.8667
1085       Aluno-1009  RA-1009            2023  ALFA 7.2450

In [31]:
#Checagem específica por RA
alunos_frequencia = df_concat['RA'].value_counts()

print("Alunos com mais registros na base histórica:")
print(alunos_frequencia.head(15))

Alunos com mais registros na base histórica:
RA
RA-860    3
RA-859    3
RA-858    3
RA-855    3
RA-854    3
RA-853    3
RA-851    3
RA-850    3
RA-847    3
RA-842    3
RA-841    3
RA-840    3
RA-837    3
RA-836    3
RA-834    3
Name: count, dtype: int64

- O conjunto de dados não contêm dados 100% duplicados, nem registros duplicados de um mesmo aluno em um ano. Porém, nota-se que existe duplicação entre anos, ou seja, um mesmo aluno foi registrado nas bases de 2022, 2023 e 2024. Isso não indica a necessidade de normalização, mas é um grande ponto de atenção para a etapa de treinamento de modelo.

###Valores únicos

Como última checagem antes de finalizar a análise, pro caso de termos algum valor não normalizados no dataset.

In [34]:
# Passa por todas as colunas do dataset
for coluna in df_concat.columns:
    print(f"--- Coluna: {coluna} ---")
    print(df_concat[coluna].unique())
    print("\n")

--- Coluna: Nota_Matematica ---
[ 2.7   6.3   5.8   2.8   7.    2.3   8.2   1.2   5.5   3.3   1.8   3.5
  8.    9.    7.2  10.    9.2   9.5   7.7   8.5   5.7   4.7   3.7   4.
  2.5   6.7   1.5   6.5   4.5   6.    3.    5.    1.7   4.8   1.3   7.5
  0.    9.3   0.3   8.7   6.2   8.3   6.8   7.8   8.8   5.3   8.4   7.3
  9.7   4.3   5.1   5.2   2.    1.    3.8   8.1   0.7   3.65  0.2   7.1
  4.2   0.5   2.2   3.2   5.4   3.1   9.8   9.4   8.9   9.6   9.1   2.9
  5.6   9.9   7.6   6.6   8.6   7.9   8.75  6.75  6.05  6.15  8.05  6.35]


--- Coluna: IAA ---
[ 8.3    8.8    0.     7.9    7.1    9.2    6.3    9.6   10.     5.
  6.7    7.5    5.8    5.4    4.6    9.5    8.5    7.4    9.     8.
  6.9    7.     6.4    6.8    8.4    3.5    7.8    8.9    7.3    5.2
  5.3    4.1    5.7    4.     5.1    4.7    1.7    6.2   10.002  8.002
  9.002  9.502  7.918  8.502  7.002  7.502  7.418  6.834  9.168  6.334
  6.918  6.418  6.249  8.418  5.834  7.917  3.498  8.751  6.25   9.585
  8.334  5.25   7.084  5.832  6.666  7.083  6.667  5.833  7.501  4.584]


--- Coluna: Fase Ideal ---
['Fase 8 (Universitários)' 'Fase 7 (3º EM)' 'Fase 6 (2º EM)'
 'Fase 5 (1º EM)' 'Fase 3 (7º e 8º ano)' 'Fase 4 (9º ano)'
 'Fase 2 (5º e 6º ano)' 'Fase 1 (4º ano)' 'ALFA  (2º e 3º ano)'
 'ALFA (1° e 2° ano)' 'Fase 1 (3° e 4° ano)' 'Fase 2 (5° e 6° ano)'
 'Fase 3 (7° e 8° ano)' 'Fase 4 (9° ano)' 'Fase 5 (1° EM)'
 'Fase 6 (2° EM)' 'Fase 7 (3° EM)']


--- Coluna: Turma ---
['A' 'D' 'B' 'C' 'F' 'K' 'L' 'H' 'P' 'E' 'G' 'I' 'M' 'N' 'J' 'Q' 'U' 'R'
 'O' 'S' 'T' 'V' 'Y' 'Z' 'ALFA A - G0/G1' 'ALFA B - G2/G3'
 'ALFA C - G0/G1' 'ALFA D - G2/G3' 'ALFA E - G2/G3' 'ALFA F - G0/G1'
 'ALFA G - G2/G3' 'ALFA H - G0/G1' 'ALFA I - G2/G3' 'ALFA J - G2/G3'
 'ALFA K - G0/G1' 'ALFA L - G2/G3' 'ALFA M - G0/G1' 'ALFA N - G2/G3'
 'ALFA O - G2/G3' 'ALFA Q - G2/G3' 'ALFA R - G0/G1' 'ALFA S - G2/G3'
 'ALFA T - G2/G3' 'ALFA U - G2/G3' 'ALFA V - G0/G1' 'ALFA Y - G0/G1' '1A'
 '1B' '1C' '1D' '1F' '1G' '1H' '1J' '1K' '1L' '1M' '1N' '1P' '1R' '2A'
 '2B' '2C' '2D' '2F' '2G' '2H' '2I' '2K' '2L' '2M' '2N' '2P' '2R' '2U'
 '3A' '3B' '3C' '3D' '3F' '3G' '3I' '3K' '3L' '3M' '3N' '3P' '4A' '4B'
 '4C' '4F' '4G' '4L' '4M' '4N' '5A' '5B' '5C' '5F' '5L' '5M' '6A' '6L'
 '7A' '1E' '3H' '3R' '3U' '4H' '4R' '5D' '5G' '5N' '7E']


--- Coluna: RA ---
['RA-1' 'RA-2' 'RA-3' ... 'RA-1227' 'RA-1228' 'RA-1229']


--- Coluna: INDE ---
[5.783      7.055      6.591      ... 7.44936667 8.24318333 7.7887    ]


--- Coluna: Nota_Portugues ---
[ 3.5   4.5   4.    2.9   5.3   5.7   0.7   6.    2.6   2.5   1.1   5.5
  0.    6.5   9.    0.5   3.1   4.7   6.3   3.8   4.4   1.5   3.6   1.6
  7.1   4.3   7.    5.1   7.3   5.8   5.2   2.8   2.2   8.    4.2   7.8
  6.2  10.    8.2   9.5   4.8   3.    8.3   1.8   7.7   5.    7.5   7.2
  6.7   3.4   6.8   3.7   2.7   3.2   8.5   1.7   2.    1.2   2.3   9.3
  5.75  3.3   9.2   1.3   8.7   1.    9.7   8.8   9.8   9.1   8.9   5.9
  9.6   6.6   7.6   7.4   9.4   8.6   8.1   6.4   4.9   6.9   8.4   5.4
  4.1   6.25  8.05  8.85  8.15]


--- Coluna: IDA ---
[ 4.          6.8         5.6         5.          5.2         3.3
  7.6         1.6         6.7         4.1         3.          1.5
  4.7         7.3         3.5         7.8         9.          8.
  3.8         8.6         6.9         3.7         7.5         6.1
  4.8         8.5         5.9         4.3         2.1         8.1
  3.9         6.2         7.          8.4         7.2         4.9
  5.8         9.3         8.7         4.5         3.6         2.5
  2.9         1.2         2.          0.          0.7         8.9
  7.1         6.          5.5         8.8         6.5         6.6
  7.4         7.7         5.7         4.6         5.3         5.4
  1.8         4.4         7.9         1.4         6.3         8.3
  3.2         2.7         5.1         2.8         3.4         3.1
  2.6         8.2         0.9         1.3         9.1         1.1
  1.7         2.3         6.4         9.5         9.8         2.4
  9.6         9.2         9.9         4.2         1.9         9.4
  1.          9.7        10.          2.2         8.25        9.25
  8.75        9.75        7.75        5.25        6.75        4.75
  7.25        2.75        6.25        3.75        2.25        5.75
  4.25        3.25        6.33333333  5.66666667  4.66666667  3.16666667
  1.75        9.66666667  3.66666667  4.83333333  6.16666667  2.66666667
  8.16666667  7.66666667  6.66666667  8.66666667  9.83333333  7.33333333
  8.83333333  5.83333333  5.33333333  5.16666667  6.83333333  2.33333333
  3.93333333  2.83333333  4.33333333  3.83333333  4.16666667  9.33333333
  8.33333333  1.66666667  1.16666667  7.83333333  7.16666667  3.33333333
  0.5         2.16666667  9.16666667  8.06666667  8.2         7.06666667
  6.06666667  7.48333333  7.36666667  6.81666667  7.65        7.21666667
  8.03333333  6.9         6.93333333  5.48333333  2.63333333  8.26666667
  6.4       ]


--- Coluna: IAN ---
[ 5.  10.   2.5]


--- Coluna: Ano Nascimento ---
<IntegerArray>
[2003, 2005, 2004, 2002, 2001, 2006, 2007, 2009, 2008, 2010, 2011, 2012, 2013,
 2014, 2015, 2016, 2017]
Length: 17, dtype: Int64


--- Coluna: IPV ---
[ 7.278       6.778       7.556       5.278       7.389       7.222
  7.667       6.278       9.5         7.056       6.389       8.056
  7.75        7.292       6.333       8.292       6.875       7.
  7.167       7.25        8.833       8.556       9.111       9.667
 10.          7.611       7.333       7.944       6.          8.944
  5.222       9.833       6.111       4.375       6.083       5.958
  7.417       7.083       7.042       8.5         7.542       6.5
  7.5         6.458       6.125       8.25        7.875       8.125
  7.917       6.167       9.417       5.917       6.889       5.833
  8.667       4.625       9.292       8.          7.625       7.458
  6.417       6.75        8.458       9.208       9.75        7.125
  6.667       9.083       9.583       6.292       6.833       7.708
  6.708       8.375       3.792       5.          5.583       7.792
  6.958       4.958       7.375       8.583       6.375       3.917
  7.583       8.208       7.958       8.083       6.542       7.208
  7.833       4.792       5.792       8.917       9.25        6.042
  8.042       8.625       4.708       3.75        4.917       6.917
  5.708       4.833       5.167       4.417       5.125       4.875
  6.208       5.333       4.542       5.5         8.417       9.125
  8.708       9.167       4.292       6.625       3.875       5.542
  5.625       6.583       5.75        3.333       3.833       5.417
  5.875       5.375       5.208       5.083       6.222       5.889
  5.056       8.389       5.944       8.278       6.611       8.611
  8.444       5.778       6.944       6.722       8.722       7.889
  8.889       3.944       8.111       6.056       7.778       8.167
  7.722       8.333       6.556       7.444       8.222       9.556
  7.111       6.444       5.556       5.444       4.5         9.333
  9.056       6.25        8.75        9.611       8.778       9.
  5.25        2.5         8.92        8.585       6.26        7.915
  8.415       8.67        5.165       6.84        6.67        9.845
  8.835       7.34        8.915       4.16        8.17        8.66
  8.665       9.09        8.83        8.16        7.995       5.84
 10.01        9.01        8.34        6.265       3.32        8.01
  9.34        8.595       8.18        6.01        7.83666667  7.94666667
  7.05666667  7.83333333  8.11333333  6.95        8.33666667  8.22333333
  8.05666667  8.28        5.68        8.085       7.01        8.925
  7.175       8.08        8.59        9.84        6.59        9.245
  9.005       6.35        8.09        6.68        7.675       5.925
  5.93        5.595       7.68        8.255       6.43        7.095
  9.51        9.255       9.67        7.6         9.085       7.02
  8.175       9.925       9.345       5.08        7.67        8.675
  8.425       7.09        8.005       7.925       6.34        8.84
  5.85        7.18        7.35        8.33        7.51        7.84
  7.415       9.755       9.415       9.76        9.585       6.16
  7.265       6.32        9.505       9.17        7.835       7.42
  8.165       7.845       5.76        7.78666667  7.44666667  8.22666667
  7.73        8.11666667  8.06        8.50333333  5.89666667  7.89333333
  9.06        6.17333333  8.95        7.78        7.06        7.61333333
  8.83666667  8.33333333  6.89333333  8.56        8.00666667  8.39
  8.45        9.39666667  7.39        7.00666667  7.56333333  9.00666667
  8.39333333  8.00333333  8.89333333  8.16666667  7.66666667  8.11
  7.44333333  8.44666667  8.44333333  7.11333333  7.94333333  8.61333333
  7.39333333  6.83666667  7.61666667  7.22333333  7.78333333  7.67333333
  8.61666667  7.45        6.89        7.27666667  7.72333333  8.62
  8.28333333  8.78333333  6.72        8.28666667  8.12        7.95
  7.33666667  7.62        6.94        8.73        8.67333333  9.28666667
  9.23        7.89        9.11666667  9.28333333  7.23333333  9.22666667
  7.06333333  7.12        7.50666667  6.39666667  7.17333333  9.6375
  8.7125      9.045       8.71        6.885       7.8775      8.7525
  9.0025      9.7625      9.0075      9.26        8.8775      8.3375
  8.4225      6.8         8.6725      8.755       8.2975      8.505
  7.13        8.13        8.38        8.7175      8.0075      8.0475
  8.7975      7.9225      7.88        9.1725      7.5875      7.92
  6.7125      7.0025      6.9175      7.46        8.0875      7.7525
  6.96        7.56        8.17333333  7.72666667  8.95333333  8.50666667
  9.06333333  8.72666667  6.94666667  9.17333333  9.62        6.78
  9.56666667  8.23        9.34333333  7.50333333  7.11666667  8.89666667
  8.84333333  8.45333333  9.67666667  8.56333333  6.78333333  9.89666667
  7.89666667  9.95333333  7.28666667  9.84333333  8.56666667  7.79
  8.17666667  8.34333333  9.67333333  7.33333333  6.10666667  5.55
  6.21666667  8.9225      6.2075      5.8275      9.175       8.0025
  7.17        8.63        6.965       6.7975      7.4625      7.5425
  6.9225      7.0075      7.1725      7.255       7.2125      8.1725
  7.545       6.5025      7.585       7.38        7.4225      8.795
  7.9575      7.7925      6.545       6.5425      8.2925      7.9175
  7.6275      7.2975      7.0875      7.505       7.335       6.6325
  7.4175      7.005       7.1325      7.2575      7.795       8.1275
  6.5875      6.715       7.71        6.7575      6.0425      7.8325
  8.2125      8.045       8.3775      7.2925      8.0425      7.05
  7.96        7.9625      7.8375      6.88        7.045       7.5025
  5.54        6.4575      7.6725      6.2475      6.5775      8.88
  6.8425      6.5825      8.42        8.46        8.2525      8.79
  8.4625      8.1225      8.5025      7.3775      7.7125      7.5475
  7.3375      8.96        9.545       9.3775      8.8325      9.5875
  8.9175      7.0425      6.05        7.3825      7.465       6.465
  7.6675      9.1275      8.295       9.21        9.2125      6.585
  6.6675      7.5075      6.8375      6.6275      7.215       5.59
  6.8725      7.8425      8.7575      7.715       6.505       5.6275
  6.4225      6.255       6.755       7.085       7.63        6.2525
  6.9625      7.755       7.8         8.3825      7.59        8.9675
  7.4675      8.385       8.8825      6.005       6.8775      8.215
  7.6325      5.44666667  7.04666667  7.21333333  4.17333333  9.73
  6.27        8.94666667  4.61        7.27333333  6.16666667  7.55333333
  6.55333333  4.72        4.33333333  6.83333333  7.22        7.11
  4.99666667  6.49333333  8.05333333  7.16333333  6.77333333  6.94333333
  6.15666667  5.38333333  5.93333333  8.38666667  6.66        6.83
  7.33        6.49        6.99        5.915       7.245       7.325
  7.83        7.665       4.75        7.24        6.575       5.66
  5.33        4.58        5.575       9.425       6.08        6.165
  6.495       6.405       7.58        6.085       6.17        6.42
  6.915       5.16        6.72333333  5.83333333  5.78333333  7.77
  3.17666667  6.99666667  7.88666667  5.10666667  5.83        6.665
  6.245       4.25        6.33333333  6.38666667  4.72666667  4.49666667
  6.61666667  4.22666667  6.61        4.22333333  5.44        7.7475
  5.92        5.8325      5.7875      6.745       8.6675      8.4975
  6.7425      5.87        5.335       5.74        8.335       5.155
  5.745       7.495       7.075       6.825       6.79        7.29
  6.6225      6.8325      6.7075      6.54        7.1675      7.04
  4.995       6.71333333  6.60666667  4.88666667  3.50666667  7.66333333
  9.45        5.21333333  7.16666667  9.56333333  5.99666667  7.05333333
  7.61        7.38333333  5.4125      7.2425      6.5375      7.5825
  5.9125      4.835       6.415       7.21        7.705       6.04
  7.54        6.4075      6.9975      6.2875      6.535       7.2475
  8.66666667  7.38666667  4.67        6.99333333  6.77        5.7525
  7.1225      9.215       6.0325      7.165       6.8275      5.7475
  6.88333333  6.71666667  5.66333333  8.72333333  9.4         6.16333333
  5.94666667  5.44333333  5.82666667  5.60666667  6.05333333  6.33
  7.55666667  6.11        5.05333333  7.32666667  5.55333333  7.77666667
  8.78666667  5.93666667  2.94333333  3.77666667  2.99666667  9.00333333
  8.55666667  5.61333333  3.1225      6.1625      7.4575      7.295
  6.58        6.705       7.3325      5.4525      4.1625      5.62
  7.1275      8.545       5.495       5.88333333  7.49666667  6.93666667
  7.10333333  5.88        6.37        6.955       6.995       8.1675
  6.7475      5.496       4.268       4.728       6.964       5.824
  5.422       6.232       8.7         5.258       5.03        7.14
  5.6175      6.1225      7.2075      9.13        6.785       6.7025
  5.9975      6.325       5.932       9.576       5.626       7.07
  6.832       5.292       8.202       7.468       8.466       6.732
  5.428       6.432       8.0825      4.705       7.0825      6.87
  7.28        7.10666667  6.82666667  6.77666667  7.1175      5.67
  6.7825      6.21        6.738       7.736       7.836       7.234
  6.158       6.966       6.998       7.698       5.066       5.534
  7.066       6.866       6.598       6.335       5.665       5.825
  6.1175      6.2025      5.96        7.3725      6.38333333  6.44333333
  7.44        7.60333333  6.55        4.94666667  7.72        5.88666667
  8.706       8.302       8.704       7.668       8.44        7.604
  8.336       9.074       8.372       8.206       7.734       7.196
  7.766       7.398       8.8375      3.545       6.7925      5.2875
  6.0375      8.5875      9.39333333  6.362       7.064       8.502
  8.47        8.87        7.936       8.636       5.764       8.464
  6.296       9.272       9.168       7.634       6.66666667  7.2875
  6.4975      8.2075      7.1625      7.4125      8.21        7.0375
  7.535       9.0475      8.5475      8.806       6.896       7.432
  7.03        8.572       8.538       5.996       7.366       7.02166667
  8.02833333  8.64333333  6.73        6.994       8.872       6.53
  6.196       8.674       8.436       6.764       7.866       7.332
  8.504       8.2         5.726       8.236       7.266       6.9
  8.672       5.862       7.566       8.74        6.03        8.965
  8.304       8.696       6.626       7.028       9.004       7.132
  6.762       6.27666667  6.27333333  6.88666667  5.7825      6.4125
  7.205       7.134       7.666       7.872       7.232       7.636
  8.404       8.172       6.798       8.004       8.068       8.334
  7.798       8.702       7.598       8.468       8.066       8.166
  9.23333333  9.62333333]


--- Coluna: IPS ---
[ 5.6     6.3     7.5     5.      6.9     8.1     8.8    10.      9.4
  4.4     3.8     2.5     8.13    8.14    3.14    7.52    8.76    3.76
  2.52    6.89    4.39    6.26    3.77    9.38    5.02    5.63    6.27
  4.38    5.64    7.51    5.01    2.51    6.88    8.135   6.255   6.885
  5.625   3.135   8.755   5.635   3.755   4.385   5.005   7.505   6.25
  9.375   4.375   8.125   8.75    6.875   7.195   6.2575  6.5675  6.57
  7.1975  6.5725  5.945 ]


--- Coluna: Ano ingresso ---
[2016 2017 2021 2018 2019 2020 2022 2023 2024]


--- Coluna: Pedra ---
['Quartzo' 'Ametista' 'Ágata' 'Topázio' 'Agata']


--- Coluna: Instituição de ensino ---
['Escola Pública' 'Rede Decisão' 'Escola JP II' 'Pública' 'Privada'
 'Privada - Programa de Apadrinhamento'
 'Privada - Programa de apadrinhamento' 'Concluiu o 3º EM'
 'Nenhuma das opções acima' 'Privada *Parcerias com Bolsa 100%']


--- Coluna: Nome Anonimizado ---
['Aluno-1' 'Aluno-2' 'Aluno-3' ... 'Aluno-1227' 'Aluno-1228' 'Aluno-1229']


--- Coluna: IEG ---
[ 4.1         5.2         7.9         4.5         8.6         8.4
  4.6         9.5         4.2         4.          7.4         8.3
 10.          8.7         9.2         8.2         8.8         7.6
  6.1         6.4         4.8         9.6         9.          5.4
  8.9         7.8         6.5         5.9         6.3         7.
  6.9         8.1         9.3         6.          9.4         9.1
  7.7         5.6         3.          6.6         2.          7.5
  3.3         3.8         2.7         6.8         7.3         9.7
  5.7         7.1         8.          0.          5.3         3.4
  8.5         5.8         6.2         4.7         3.5         9.9
  9.8         7.2         5.1         3.6         4.3         6.7
  4.9         3.7         2.8         2.9         3.9         5.
  5.5         4.4         3.1         8.66666667  9.33333333  9.08333333
  9.75        4.16666667  8.61363636  9.54545455  8.81818182  8.11363636
  9.29545455  7.40909091  9.23076923  9.04545455  9.34782609  9.52380952
  8.83022774  5.05175983  9.30641822  7.98136646  9.44444444  4.77272727
  9.49494949  6.88636364  5.6937799   9.52272727  8.44444444  3.15909091
  9.76190476  7.88636364  8.44565217  6.64335664  7.63888889  8.75
  2.91666667  5.41666667  7.95751634  8.71052632  7.67105263  9.47368421
  8.69736842  5.83333333  7.44565217  9.16666667  9.375       9.16666667
  8.33333333  8.125       8.54166667  8.33333333  8.6631016   8.20855615
  7.07219251  2.75252525  8.14171123  7.33201581  4.59893048  7.00534759
  6.48395722  4.69251337  7.68716578  8.69444444  9.25        5.75163399
  6.83333333  7.77941176  8.94444444  8.16666667  8.41666667  8.875
  8.58333333  9.29166667  8.20833333  7.29166667  7.25        9.41176471
  6.25        9.54451346  6.20082816  4.72222222  8.66071429  8.39285714
  9.24603175  7.61904762  9.51190476  8.79761905  9.45906433  6.61904762
  8.05952381  8.78571429  9.02380952  9.03571429  7.83333333  6.39285714
  9.73684211  8.59133127  8.38888889  8.36363636  6.52272727  7.90909091
  8.38636364  6.47727273  9.31818182  8.56818182  7.86363636  7.38095238
  7.00181159  7.70833333  6.875       7.01086957  9.79166667  6.60326087
  9.2826087   8.38043478  8.63043478  8.72222222  6.97826087  8.88043478
  9.61538462  9.5326087   9.28571429  8.68421053  8.78446115  9.02255639
  9.26065163  7.56892231  8.7593985   8.21428571  5.625       8.18181818
  7.72727273  9.30735931  9.09090909  9.77272727  7.72727273  9.55533597
  9.32806324  5.93873518  9.10079051  6.13636364  6.65019763  7.32213439
  7.05533597  8.63636364  8.79545455  8.88888889  9.27272727  7.84090909
  9.02272727  7.95454545  4.54545455  8.86363636  8.40909091  9.09090909
  4.6969697   8.59307359  9.2965368   5.38961039  9.58333333  7.54940712
  9.56439394  8.27651515  4.77272727  9.33712121  8.48484848  8.67424242
  9.12878788  3.95256917  7.99407115  7.29249012  8.64624506  6.42857143
  4.62450593  5.29644269  5.52083333  6.77777778  5.3125      6.43939394
  6.79761905  5.8452381   5.53359684  8.03030303  7.34848485  5.79545455
  8.09523809  5.95238095  9.04761905  9.04761905  6.9047619   8.33333333
  9.28571429  6.9047619   8.85620915  7.85714286  7.74327122  9.06832298
  8.89233954  8.67494824  9.10973085  5.27777778  6.01778656  9.54545455

Ainda se faz necessária a normalização da coluna Gênero:

In [35]:
# Cria o dicionário de mapeamento
mapeamento_genero = {
    'Menina': 'Feminino',
    'Menino': 'Masculino'
}

# Aplica a substituição na coluna Gênero
df_concat['Gênero'] = df_concat['Gênero'].replace(mapeamento_genero)

print(df_concat['Gênero'].value_counts())

Gênero
Feminino     1519
Masculino    1326
Name: count, dtype: int64

## 5. Exportando a Base Tratada

In [36]:
# Define o path de saída
processed_path = Path("../data/processed")

# Cria a pasta/path se ele não existir
processed_path.mkdir(parents=True, exist_ok=True)

# Exporta a base tratada
df_concat.to_csv(processed_path / "passos_magicos_clean_eda.csv", index=False, encoding="utf-8")

In [37]:
# Verificando se a base foi salva corretamente
os.listdir("../data/processed")

['passos_magicos_clean_eda.csv']